### PR TITLE
src/compliment/core.clj: Use ns -> nspc as a local

### PR DESCRIPTION
**Pull request by abo-abo**
Don't want to shadow `clojure.core/ns'.

### CODE REVIEW

**Comment by alexander-yakushev** [comment]
Hey, thanks for the PR, I'm going to merge this, but can you please tell me what problem you have with this? Is this to satisfy some linter, maybe?

**Comment by abo-abo** [comment]
I was debugging your package (thanks, btw) to figure out how it works.

My debugger works like this:

```clojure
(lispy-clojure/dest
  '[{:keys [nspc context sort-order sources extra-metadata]
     :or {sort-order :by-length}} options-map])
;; =>
;; (do
;;   (def map__7847 options-map)
;;   (def map__7847
;;     (if (clojure.core/seq? map__7847)
;;       (clojure.lang.PersistentHashMap/create
;;         (clojure.core/seq map__7847))
;;       map__7847))
;;   (def nspc
;;     (clojure.core/get
;;       map__7847
;;       :nspc))
;;   (def context
;;     (clojure.core/get
;;       map__7847
;;       :context))
;;   (def sort-order
;;     (clojure.core/get
;;       map__7847
;;       :sort-order :by-length))
;;   (def sources
;;     (clojure.core/get
;;       map__7847
;;       :sources))
;;   (def extra-metadata
;;     (clojure.core/get
;;       map__7847
;;       :extra-metadata))
;;   {:nspc nspc,
;;    :context context,
;;    :sort-order sort-order,
;;    :sources sources,
;;    :extra-metadata extra-metadata})
```

The above call won't work if we use `ns`, Clojure won't allow to rebind it.

**Comment by alexander-yakushev** [comment]
I see.

Actually, I can't merge it as is, because `:ns`in the options-map is part of the public API. Instead of renaming it in the destructuring map you'd have to extract like `(let [nspc (:ns options-map)])`.

**Comment by abo-abo** [comment]
> you'd have to extract it like (let [nspc (:ns options-map)])

OK, I've added this.

**Comment by alexander-yakushev** [comment]
Thanks! I've rebased and merged it.

**Pull request closed without merging**
