### PR TITLE
Also macroexpand `some->`, `some->>`

### PR DESCRIPTION
**Pull request by vemv**
Fixes https://github.com/alexander-yakushev/compliment/issues/109

Cheers - V

### CODE REVIEW

**Comment by alexander-yakushev** [comment]
Neat, thanks!

**Comment by vemv** [comment]
Cheers! Release appreciated.

**Comment by alexander-yakushev** [comment]
0.4.4-SNAPSHOT

**Comment by alexander-yakushev** [comment]
@vemv `0.4.4` to hop onto CIDER release bandwagon.

**Comment by vemv** [comment]
It's in 🚂

**Pull request merged**
