### PR TITLE
Revert "Port the cljs-tooling completion machinery to compliment"

### PR DESCRIPTION
**Pull request by arichiardi**
This reverts commit f8996a0ad94c682ef5e19f6c16621131b86c5617 - the project.clj
conflict got resolved while doing so.

### CODE REVIEW

**Comment by bbatsov** [comment]
👍

**Comment by alexander-yakushev** [comment]
Thank you! Sorry for the time wasted :(

**Comment by arichiardi** [comment]
No worries no time has been wasted, the cljs part was actually used in Clorine I think so let's make sure we break it as less as possible 😎

**Comment by bbatsov** [comment]
Btw, it probably makes sense to change the snapshot version to 0.3.x and maybe cut a release with that one improvement was added a while ago.

**Pull request merged**
